<a href="https://colab.research.google.com/github/sw01-prog/python_coding_practice/blob/main/Copy_of_python_revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 X = [1,5,9,0]
 Y = [3,0,2,9]

In [ ]:
# prompt: intersection of both th esets

X = [1,5,9,0]
Y = [3,0,2,9]

intersection = list(set(X) & set(Y))
intersection


[0, 9]

 Given an array, find all the duplicates in this array? For example: input: [1,2,3,1,3,6,5] output: [1,3]

In [ ]:
X=[1,2,3,1,3,6,5]

In [ ]:
s=[]
dup=[]
for n in X:
 if n in s:
   dup.append(n)
 else:
    s.append(n)

In [ ]:
print(dup)

[1, 3]


set as empty list - unique feature as it cannot contain duplicate values.

In [ ]:
X=[10,5,8,7,2]

In [ ]:
def max_prod(x):
 x.sort()
 return(x[-1]*x[-2]*x[-3])

In [ ]:
57

prime nos

In [ ]:
x= int(input())
for d in range(2, x):
    if x%d== 0:
      print(False)
    else:
      print(True)

87
True
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [ ]:
x= int(input())
x= int(input())
n = x # Assuming you want to iterate up to x.  If not, replace x with the intended limit.
for d in range(2, n):
    if x%d== 0:
        print(False) # Use print to display the boolean value
        break #Exit loop after finding a divisor
else:
    print(True) # Execute if loop completes without finding divisors



8


SyntaxError: 'return' outside function (<ipython-input-3-16964a90331b>, line 4)

In [ ]:
def is_prime(x):  # give the function a more descriptive name
  x = int(input("Enter a number: "))  # move input prompt inside function for clarity
  for d in range(2, x):  # change n to x, iterate till x (exclusive)
    if x % d == 0:
      return False  # use boolean False, correct indentation
  else:
    return True  # use boolean True, correct indentation

In [ ]:
x = int(input())
for d in range(2, x):
  if x%d==0:
   print(false)
   .break

  else:
    print(true)

6


NameError: name 'false' is not defined

Given an integer array, find the sum of the largest contiguous subarray within the array. For example, given the array A = [0,-1,-5,-2,3,14] it should return 17 because of [3,14]. Note that if all the elements are negative it should return zero.

Numpy function np if the below function generate random numbers.

In [ ]:
import numpy as np
a= np.empty((3), dtype=float)
print(a)

[0.  0.5 1. ]


In [ ]:
import numpy as np
a= np.empty((2,2), dtype=int)
print(a)

[[          827675652                   0]
 [7738144531864184948          4294979187]]


In [ ]:
a = np.arange(0,40,3, dtype=float)
print(a)

[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36. 39.]


In [ ]:
np.linspace(5,10,20, endpoint= False, retstep=True)

(array([5.  , 5.25, 5.5 , 5.75, 6.  , 6.25, 6.5 , 6.75, 7.  , 7.25, 7.5 ,
        7.75, 8.  , 8.25, 8.5 , 8.75, 9.  , 9.25, 9.5 , 9.75]),
 np.float64(0.25))

euclidean distance code - manual



In [ ]:
x1= int(input())
y1= int(input())
x2= int(input())
y2= int(input())

5
3
6
9


In [ ]:
import math

In [ ]:
a = math.sqrt((x1-x2)**2+(y2-y1)**2)

In [ ]:
print(a)

6.082762530298219


In [ ]:
import numpy as np
a= np.array([2,6,9])
b= np.array([9,1,3])
d= np.linalg.norm(a-b)
print(d)

10.488088481701515


numpy eye function

In [ ]:
import numpy as np
a= np.eye(3,4,k=-1, dtype=int)

In [ ]:
print(a)

[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]]


In [ ]:
a= np.eye(3,4,k=3, dtype=int)

In [ ]:
print(a)

[[0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
a= np.eye(3,4,k=0, dtype=int)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


Generate random nos

In [ ]:
np.random.rand(3,4)

array([[0.37160523, 0.76164014, 0.43221795, 0.35137149],
       [0.50182874, 0.19629064, 0.11890291, 0.73826663],
       [0.76331689, 0.44380562, 0.68559355, 0.28742635]])

In [ ]:
np.random.randint(0,10,size=(3,4))
#np.random.randint(low, high, size)

array([[1, 4, 3, 6],
       [9, 9, 8, 2],
       [3, 0, 1, 4]])

Given an integer n and an integer K, output a list of all of the combination of k numbers chosen from 1 to n. For example, if n=3 and k=2, return [1,2],[1,3],[2,3]


In [ ]:
from itertools import combinations
def find_combinations (n,k):
 return list(combinations(range(1,n+1),k))
 find_combinations(3,2)

In [ ]:
print(find_combinations(5,2))

[(1, 2), (1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5), (3, 4), (3, 5), (4, 5)]


Write a function to generate N samples from a normal distribution

In [ ]:
# prompt:  generate N samples from a normal distribution

import numpy as np

def generate_normal_samples(n, mean=0, std_dev=1):
  """Generates N samples from a normal distribution.

  Args:
    n: The number of samples to generate.
    mean: The mean of the normal distribution.
    std_dev: The standard deviation of the normal distribution.

  Returns:
    A NumPy array containing the generated samples.
  """
  return np.random.normal(loc=mean, scale=std_dev, size=n)


In [ ]:
import numpy as np
def generate_n_samples (n, mean=0, std_dev=1):
  return np.random.normal(loc=mean, scale=std_dev, size=n)
print(generate_n_samples(5))

[ 1.13979196 -0.53488709  1.14007354 -1.08026784  0.10107608]


Given a string, return the first recurring character in it, or “None” if there is no recurring character. Example: input = "pythoninterviewquestion" , output = "n"

In [ ]:
def repeat_python_string(s):
 seen=set()
 for char in s:
  if char in seen:
   return char
  seen.add(char)
 return "None"


In [ ]:
input_str = "pythoninterviewquestion"
result = repeat_python_string(input_str)
print(result)

n


Given a string, return the recurring characters in it, or “None” if there is no recurring character. Example: input = "pythoninterviewquestion" , output = "n"

In [ ]:

def recurring_characters(s):
 seen=set()
 recur=set()
 for char in s:
  if char in seen:
   recur.add(char)
  else:
    seen.add(char)
 return list(recur) if recur else "None"



In [ ]:
input_str= "pythoninterviewquestion"
result= recurring_characters(input_str)
print(result)

['e', 'o', 't', 'i', 'n']


 Given a positive integer X return an integer that is a factorial of X. If a negative integer is provided, return -1. Implement the solution by using a recursive function.

In [ ]:
def factorial (x):
 if x<0:
  return -1
 elif x==0 or x==1:
  return 1
 else:
  return x*factorial(x-1)

In [ ]:
x=int(input())
print(factorial(x))



-2
-1


for factorial how to write it in code- x*factorial(x-1)(this is recursive logic)


webscraping

In [ ]:
import requests
from bs4 import BeautifulSoup
#requests: to send HTTP requests and get webpage content.

#BeautifulSoup: to parse the HTML content and extract information from it.


url = 'http://books.toscrape.com/'
response = requests.get(url)
#url: the website's homepage containing a list of book categories.

#requests.get(url): sends a GET request to the site and stores the server's response in response.


if response.status_code == 200:
  #Checks if the request was successful (HTTP status code 200 means OK).

#If the site is reachable and the page is fetched correctly, we proceed.


    soup = BeautifulSoup(response.text, 'html.parser')
    #Parses the page content (response.text) into a navigable tree structure using BeautifulSoup.

#'html.parser': built-in parser for processing HTML.


    ul_element= soup.find('ul', class_='nav-list')
    #Finds the first <ul> (unordered list) element with class "nav-list".

#This <ul> contains the category links on the sidebar.


    category_links = ul_element.find_all('a')[1:]
    #Finds all <a> tags (hyperlinks) inside the ul_element.

#[1:] skips the first link, which is usually “Books” (a header, not a real category).


    for link in category_links:
        category_name= link.get_text(strip=True)
        print(category_name)
       # Loops over each category <a> tag.

#link.get_text(strip=True) extracts the visible text (category name) and removes whitespace.

#print(category_name) displays the list of categories.


else:
    print('failed:',response.status_code)
    #If the request fails (e.g., status code 404, 500), print an error message.




Travel
Mystery
Historical Fiction
Sequential Art
Classics
Philosophy
Romance
Womens Fiction
Fiction
Childrens
Religion
Nonfiction
Music
Default
Science Fiction
Sports and Games
Add a comment
Fantasy
New Adult
Young Adult
Science
Poetry
Paranormal
Art
Psychology
Autobiography
Parenting
Adult Fiction
Humor
Horror
History
Food and Drink
Christian Fiction
Business
Biography
Thriller
Contemporary
Spirituality
Academic
Self Help
Historical
Christian
Suspense
Short Stories
Novels
Health
Politics
Cultural
Erotica
Crime


When web scraping, figuring out the ul and its class (or any tag and attribute) is about inspecting the HTML structure of the webpage. There's an inspect option when you right click on the content that you want from where you can identify out its class and ul. Here's how you can do it step-by-step:

1. Open Developer Tools in Your Browser
Right-click on the element you want to scrape (e.g., a list on the page).

Click Inspect or press Ctrl+Shift+I (Cmd+Option+I on Mac).

🔍 2. Locate the <ul> (unordered list) Tag
In the HTML pane that opens:

Look for the structure like this:

html
Copy
Edit
<ul class="some-class-name">
    <li>Item 1</li>
    <li>Item 2</li>
</ul>
The class is what helps uniquely identify the tag for scraping.

🔍 3. Note Down Tag and Class
Example:

Tag: ul

Class: some-class-name

You’ll use this in your scraping code:

python
Copy
Edit
soup.find('ul', class_='some-class-name')


In [ ]:
html = '<!DOCTYPE html><html><head><title>Learning Beautiful Soup</title></head>\
<body><h1> About Us </h1><div class = "first_div"><p>Coding Ninjas Website</p>\
<a href="https://www.codingninjas.in/">Link to Coding Ninjas Website</a>\
<ul><li>This</li><li>is</li><li>an</li><li>unordered</li><li>list.</li></ul>\
</div><p id = "template_p">This is a template paragraph tag</p>\
<a href = "https://www.facebook.com/codingninjas/">\
This is the link of our Facebook Page</a></body></html>'

In [ ]:
from bs4 import BeautifulSoup as bp
data=bp(html, 'html.parser')
arr= data.div.attrs
print(arr)


{'class': ['first_div']}


In [ ]:
for i in arr:
  print(i)

class


Problem Statement:
You are given the HTML content of a webpage, your task is to:

Print the difference between the number of descendants and the number of children of the html tag

NOTE : You are provided the HTML content inside variable html

In [ ]:
## HTML Code is provided in variable html

html = '<!DOCTYPE html><html><head><title>Navigate Parse Tree</title></head>\
<body><h1>This is your Assignment</h1><a href = "https://www.google.com">This is a link that will take you to Google</a>\
<ul><li><p> This question is given to test your knowledge of <b>Web Scraping</b></p>\
<p>Web scraping is a term used to describe the use of a program or algorithm to extract and process large amounts of data from the web.</p></li>\
<li id = "li2">This is an li tag given to you for scraping</li>\
<li>This li tag gives you the various ways to get data from a website\
<ol><li class = "list_or">Using API of the website</li><li>Scrape data using BeautifulSoup</li><li>Scrape data using Selenium</li>\
<li>Scrape data using Scrapy</li></ol></li>\
<li class = "list_or"><a href="https://www.crummy.com/software/BeautifulSoup/bs4/doc/">\
Clicking on this takes you to the documentation of BeautifulSoup</a>\
<a href="https://selenium-python.readthedocs.io/" id="anchor">Clicking on this takes you to the documentation of Selenium</a>\
</li></ul></body></html>'

## Print the required output in given format

In [ ]:
from bs4 import Beautifulsoup as bp
data=bp(html, 'html.parser')
descendents=list(data.html.descendents)
children=list(data.html.children)
print(len(descendents)-len(children))


ImportError: cannot import name 'Beautifulsoup' from 'bs4' (/usr/local/lib/python3.11/dist-packages/bs4/__init__.py)

Problem Statement:
You are given the HTML content of a webpage, your task is to:

Print the name of all the tags in different lines that have an id attribute.

NOTE : You are provided the HTML content inside variable html

Output Format :
tag1
tag2
.
.

In [ ]:
## HTML Code is provided in variable html

html = '<!DOCTYPE html><html><head><title>Navigate Parse Tree</title></head>\
<body><h1>This is your Assignment</h1><a href = "https://www.google.com">This is a link that will take you to Google</a>\
<ul><li><p> This question is given to test your knowledge of <b>Web Scraping</b></p>\
<p>Web scraping is a term used to describe the use of a program or algorithm to extract and process large amounts of data from the web.</p></li>\
<li id = "li2">This is an li tag given to you for scraping</li>\
<li>This li tag gives you the various ways to get data from a website\
<ol><li class = "list_or">Using API of the website</li><li>Scrape data using BeautifulSoup</li><li>Scrape data using Selenium</li>\
<li>Scrape data using Scrapy</li></ol></li>\
<li class = "list_or"><a href="https://www.crummy.com/software/BeautifulSoup/bs4/doc/">\
Clicking on this takes you to the documentation of BeautifulSoup</a>\
<a href="https://selenium-python.readthedocs.io/" id="anchor">Clicking on this takes you to the documentation of Selenium</a>\
</li></ul></body></html>'

## Print the required output in given format

 Explanation
data: This is a BeautifulSoup object, likely created from HTML content (e.g., soup, or a smaller HTML section).

.find_all(...): This method searches for all tags that match certain criteria.

id=True: This is a filter — it tells BeautifulSoup to find all tags that have an id attribute, regardless of the tag name.

In [ ]:
from bs4 import Beautifulsoup as bp
data=(html, 'html.parser')
at=data.find_all(id=True)
for i in at:
  print(i)

ImportError: cannot import name 'Beautifulsoup' from 'bs4' (/usr/local/lib/python3.11/dist-packages/bs4/__init__.py)

airflow project

In [ ]:
from airflow import dag
from airflow.operators.python import pythonoperator
from datetime import datetime, timedelta
import pandas as pd

from airflow import DAG:

This line imports the DAG class from the airflow package.
A DAG (Directed Acyclic Graph) is the fundamental unit of workflow definition in Airflow. It represents a series of tasks with their dependencies and scheduling information.
2. from airflow.operators.python import PythonOperator:

This line imports the PythonOperator class from the airflow.operators.python module.
A PythonOperator is a type of task that executes a Python function. It's commonly used to perform custom data processing or integrations within your Airflow DAG.
3. from datetime import datetime, timedelta:

This line imports the datetime and timedelta classes from the built-in datetime module.
The datetime class represents a specific point in time, while the timedelta class represents a duration of time. These are essential for defining schedules and time-based conditions in your DAG.
4. import pandas as pd:

This line imports the pandas library, which is a powerful data analysis and manipulation tool for Python.
Pandas provides data structures like DataFrames and Series, which are widely used for handling and transforming data efficiently.

In [ ]:
file_path= ""

In [ ]:
default argument= {'owner':'airflow',
'depends_on_past': False,
                   'start_date': datetime(2025, 07, 08),
                   'retries':1,
                   'retry_delay': timedelta(min=2),}

Breakdown of the arguments:

owner: 'airflow'`
Sets the owner of the DAG to “airflow”. This is a useful metadata field for tracking who created or is responsible for the DAG.
depends_on_past: False`

Specifies that tasks in this DAG do not depend on the successful completion of their predecessors. If set to True, a task will only run if all previous tasks in the DAG have completed successfully.
start_date: datetime(2024, 8, 12)`

Sets the starting date for the DAG to August 12, 2024. This determines when the DAG will first be scheduled for execution.
retries: 1`

Configures the maximum number of times a task can be retried if it fails. In this case, a task will be retried once if it fails.
retry_delay: timedelta(minutes=2)`
Sets the delay between retries for failed tasks. If a task fails, it will be retried after a delay of 2 minutes.

Automation in airflow

In [ ]:
from airflow import dag
from airflow.operatot.python import pythonoperator
from datetime import datetime, timedelta
import pandas as pd


In [ ]:
default_args= {'owner'='airflow'
'startdate'= datetime(2025,07,09)
'depends_on_past'=False
               'retries'=1
               'retry_time'=datetime.timedelta(min=2)}

Defining Dag

In [ ]:
dag = DAG('bhav_copy_downloader',      # 🏷️ DAG ID: Unique name of the DAG
          default_args=default_args    # 📦 Default arguments applied to all tasks
          schedule_interval= 30 16 ** 1-5   # ⏰ Cron schedule: 4:30 PM Mon–Fri
          catch_up = False)                    # 🚫 Prevents backfilling old missed dates

🕒 Run Schedule Explained
Field	Value	Meaning
Minute	30	At minute 30
Hour	16	At 4 PM (16:00)
Day of month	*	Every day
Month	*	Every month
Day of week	1-5	Monday to Friday only



check if today is a trading day

In [ ]:
Holiday_file= "/home/airflow/config/nse_holidays.csv"
 (# Read CSV and convert to date objects
    holidays_df = pd.read_csv(HOLIDAY_FILE, parse_dates=["date"])
    holiday_dates = holidays_df["date"].dt.date.tolist()#will have to check if this is needed or not)
def is_trading_day():
  today= datetime.date.today()
  #This gets the current date in the format YYYY-MM-DD (e.g., 2025-07-08).
#datetime.date.today() returns a date object (not datetime with time).
  weekday= today.weekday()
   if weekday=>5:
    raise valueError('nt')
   elif today in Holiday_file:
    raise valueError('nt')
   else:
    print('trading day')



weekday() returns an integer:

0 = Monday

1 = Tuesday

...

5 = Saturday

6 = Sunday

So if weekday >= 5 means:

Saturday (5)

or Sunday (6)

👉 If true, it raises an exception to stop the DAG, with the message:
"Today is a weekend — no trading."



In [ ]:
def download_bhav_copy():
  #get today's date
  today=datetime.datetime.now()
  date_str= today.strftime('%d%b%Y').upper()
  month= today.strftime("%b").upper()
  year= today.strftime(%Y).upper()


datetime.datetime.now() → gets the current date and time.

strftime("%d%b%Y") → formats it like 08JUL2025 (required by NSE URL).

.upper() → ensures the month is capitalized (JUL, not Jul).

These are used to construct the Bhav Copy file URL.

Step 2: Construct NSE Bhav Copy URL

In [ ]:
url = f"https://www1.nseindia.com/content/historical/EQUITIES/{year}/{month}/cm{date_str}bhav.csv.zip"
headers = {"User-Agent": "Mozilla/5.0"}

Constructs the download URL based on today's date.

Example for July 8, 2025:
https://www1.nseindia.com/content/historical/EQUITIES/2025/JUL/cm08JUL2025bhav.csv.zip

The User-Agent header is needed because NSE blocks some requests if it doesn't detect a browser-like client.



Step 3: Create a Save Directory

In [ ]:
save_path = f"/home/airflow/bhavcopy/{year}-{month}-{today.day}"
os.makedirs(save_path, exist_ok=True)

Constructs a path like /home/airflow/bhavcopy/2025-JUL-8

os.makedirs(..., exist_ok=True) ensures the folder is created if it doesn’t exist.

Step 4: Download the ZIP File

In [ ]:
response = requests.get(url, headers=headers)
if response.status_code != 200:
    raise Exception("File not found or NSE site error.")

Downloads the ZIP file from NSE.

If the status code is not 200 OK, it raises an exception — i.e., something went wrong (file not available, holiday, etc.).

 Save the ZIP Locally

In [ ]:
zip_path = os.path.join(save_path, "bhav_copy.zip")
with open(zip_path, "wb") as f:
    f.write(response.content)

Saves the ZIP file as bhav_copy.zip inside the folder created above.

 Extract ZIP File

In [ ]:
with ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(save_path)

Opens the zip file.

Extracts its contents (usually one CSV file) into the same folder.

In [ ]:
    print("✅ Bhav Copy downloaded and extracted.")

    except Exception as e:
        print(f"❌ Download failed: {e}")


In [ ]:
# DAG tasks
check_trading_day = PythonOperator(
    task_id='check_trading_day',
    python_callable=is_trading_day_from_file,
    dag=dag,

This defines an Airflow task:

Element	Value
task_id	'check_trading_day'
python_callable	is_trading_day_from_file
dag	dag object (previously defined)

🔗 This is likely the first task in your DAG that ensures the Bhav Copy will only be downloaded if today is a trading day.

In [ ]:
download_task = PythonOperator(
    task_id='download_bhav_copy',
    python_callable=download_bhav_copy,
    dag=dag,
)

# DAG flow
check_trading_day >> download_task

Write  a program to check string1 and string2 are same based on number of charaters and length.

In [ ]:
string1= 'abd'
string2='dba'
if len(string1)==len(string2):
 print(True)
else:
 print(False)

True


In [ ]:
if string1 == string2:
 print(True)
else:
  print(False)

False


# string1==string2 finds out if the string are identical in the same order if they are in different order then it wont give us the desired result.
 but using sorted(string1) = sorted(string2) it would first arrange in an order then it would tell us if they are identical or not.

In [ ]:
if sorted(string1)==sorted(string2):
  print(True)
else:
  print(False)

# we can also use count(string1)

# we cannot use counter directly on integer or float we have to convert it to string first

In [ ]:
from collections import Counter # Import Counter from collections
num1 = 348
num2 = 834
if counter(num1) == counter(num2): # Convert integers to strings
  print(True)
else:
  print(False)

NameError: name 'Sorted' is not defined

Use Cases of Comparison Operators:
Equality Comparison (==) or < , >:
Conditional Statements:
Used in if, elif
Loops:



# Get the minimum value from list without using comparision operator


In [ ]:
list= [1, 2,7, 4, 3]

In [ ]:

print(sorted(list)[0])

1


# Lambda (Reverse list)

In [ ]:
print(sorted(list, key=lambda x:-x))  #sorting in reverse direction

[7, 4, 3, 2, 1]


Can also use slice to reverse a list

In [ ]:
print(list[::-1])

[3, 4, 7, 2, 1]


not giving good result

# Implement string reversal , what are different ways you can do that



slicing

In [ ]:
string = 'swayista'
print(string[::-1])

atsiyaws


using reverse function

In [ ]:
string = 'swayista'
r_v = ''.join(reversed(string))
print(r_v)

atsiyaws


Print total occurence of a word in each line print line text with number


In [ ]:
text = """This is a test line.
Another test line with the word test twice: test.
No matches here.
Test is at the beginning.
Ending with test."""

In [ ]:
lines = text.split('\n')
word = 'test'

In [ ]:
print(lines)

['This is a test line.', 'Another test line with the word test twice: test.', 'No matches here.', 'Test is at the beginning.', 'Ending with test.']


In [ ]:
word_lower = word.lower()
for i, line in enumerate(lines):
  line_lower = line.lower()
  count = line_lower.count(word_lower)
  print(f"Line {i+1}: {line} (Count: {count})")

NameError: name 'lower' is not defined

This is the correct code copied from chatgpt

In [ ]:
text= ''
lines= text.splitlines()
for line_numbers, line_text enumerates(starts, 1)
words_in_line= line_text.lower().split()
wor_count= word_in_line.count(word_find.lower())
# Print the result
    print(f"Line {line_number}: {line_text} (Occurrences of '{word_to_find}': {word_count})")


Reverse the word order in a sentence

In [ ]:
sentence= ''
def reverse_word(sentence)
 return.''join(sentence.split()[::-1])

In [ ]:
print(reverse_word(sentence))

Count the number of unique words in a string array


In [ ]:
words=[]
def count_unique_words(words):
  return len(set(words))

set(words) — converts the list of words into a set, which automatically removes duplicates.

len(...) — returns the number of unique elements in that set.



Write a program to print the first non-repeating character in a string.


In [ ]:
char_count = {}
def first_non_repeating_char(string):

  for char in string:
    if char in char_count:
      char_count[char] += 1

    else:

      char_count[char] = 1
print(first_non_repeating_char('Manshuu'))
print(char_count)

None
{'M': 1, 'a': 1, 'n': 1, 's': 1, 'h': 1, 'u': 2}


In [ ]:
s = "swiss"

for ch in s:
    if s.count(ch) == 1:
        print("First non-repeating character:", ch)
        break
else:
    print("No non-repeating character found.")


Module- A file containing somebody else's code which can be implemented in our project.

Pip is a package manager in python it is uesd to install modules.
Thre are two types of modules
1. built in e.g. os, re
2. external ones e.g.- flask

REPL- READ, EVALUATE, PRINT, LOOP

In [ ]:
pip install pyjokes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 kB 2.3 MB/s eta 0:00:00


In [ ]:
import pyjokes
Jokes= pyjokes.get_joke()
print(Jokes)

Debugging is like being the detective in a crime drama where you are also the murderer.


We can print multiple lines(strings) by using ('''    ''') triple quotes

In [ ]:
print(''' When I was young,
Nostalgia was a tiny, tiny stamp,
Me on this side,
Mother on the other side.
When I grew up,
Nostalgia was a narrow boat ticket,
Me on this side,
Bride on the other side.
But later on,
Nostalgia was a lowly grave,
Me on the outside,
Mother on the inside.
And at present,
Nostalgia becomes a shallow strait,
Me on this side,
Mainland on the other side.

''')

 When I was young,
Nostalgia was a tiny, tiny stamp,
Me on this side,
Mother on the other side.
When I grew up,
Nostalgia was a narrow boat ticket,
Me on this side,
Bride on the other side.
But later on,
Nostalgia was a lowly grave,
Me on the outside,
Mother on the inside.
And at present,
Nostalgia becomes a shallow strait,
Me on this side,
Mainland on the other side.




In [ ]:
pip install pyttsx3

In [ ]:
import pyttsx3
engine = pyttsx3.init()

# For Mac, If you face error related to "pyobjc" when running the `init()` method :
# Install 9.0.1 version of pyobjc : "pip install pyobjc>=9.0.1"

engine.say("I will speak this text")
engine.runAndWait()

RuntimeError: This means you probably do not have eSpeak or eSpeak-ng installed!

The os module in Python is a built-in standard library module that provides a way to interact with the operating system.

In [ ]:
import os

# Get the current working directory
current_directory = os.getcwd()

# Print the directory
print("The current working directory is:", current_directory)

The current working directory is: /content


A variable is a name given to the memory location of python.

Data types in python-
#String
#Integer
#Float
#Boolean
#None

Operators in python

1.   Arithmatic operator:+,-,*./ etc
2.   Assignment operators: =,+=,-= etc.
3.   Comparison operators: ==, <, >=, != etc.
4. Logical operators: and, or, not




In [ ]:
x = 10
x += 5  # x is now 15
print(x)

15


Type and type casting- used to find the data type

Converting one data type to another

In [ ]:
s=str(32)
i=int(42.9)
f=float(56)
print(s,i,f)

32 42 56.0


In [ ]:
str(32)

'32'

In [ ]:
a=(int(input()))

30


In [ ]:
a= input()
b= input()
def sum_num(a,b):
 return a+b

In [ ]:
print(sum_num(a,b))

In [ ]:
a=str(input())
b= str(input())
def string_add(a,b):
 return a+b

manshu
bakra


In [ ]:
print(string_add(a,b))

manshubakra


write a program to find the remainder when a number is didvided by z

In [ ]:
a= int(input())
z= int(input())
def remainder(a,z):
 return a%z

In [ ]:
print(remainder(a,z))

check the type of variable assigned using input function

In [ ]:
a= int(input())
print(type(a))

Use comparison parameter to find out whether a given variable a is greater than b or not. a= 34 b= 80

In [ ]:
a=34
b=80
def comparison(a,b):
 if a>=b:
  return True
 else:
  return False

In [ ]:
print(comparison(a,b))

False


To calculate square and avg of numbers inputed  by users

In [ ]:
a= float(input())
b=float(input())
def square_avg(a,b)
 return a**b
 return (a+b)/2

correct one if you want to do so many task in the function

In [ ]:
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))

def square_avg(a, b):
    square_a = a ** 2
    square_b = b ** 2
    average = (a + b) / 2
    return square_a, square_b, average

sl= name[ind_start:ind_end]


*   first index included
*   last index not included



# s1[0:3] returns 'har' characters from 0 to 3
# s1[1:3] returns 'ar' characters from 1 to 3

letters[:4]
Means: Start from the beginning, and stop before index 4

letters[1:]
Means: Start from index 1, and go to the end

Slicing with skip value-


*   letters[0:4:2]
*   the last value tells us how much would we skip



#len('harry')
#string.endswith('s')
#string.count('c')
#string.capitalize()
#strig.find('world')
#string.replace('world','python')


# \n- newline,
# \t-tab

write a python program to display a user eneterd name followed by good afternoon using input function

In [ ]:
s= str(input())
print(f'goodafternoon: {s}')

montu
goodafternoon: montu


to detect double space in a string

In [ ]:
s= input()
if " " in s:
  print(True)
else:
  print(False)

masugoodstead
False


In [ ]:
# An original string with single spaces
es = "This sentence has single spaces."

# Use the replace() method to change single spaces to double spaces
modified_sentence = es.replace(" ", "  ")


print("Modified sentence:", modified_sentence)

Modified sentence: This  sentence  has  single  spaces.


In [ ]:
es= ' i want you'
mod= es.replace('','')
print(mod)

 i want you


add or remove space

In [ ]:
s= input()
mod_s= ''.join(s.split()) # Split the string into words and rejoin with single space

ugami sin


In [ ]:
print(mod_s)

ugamisin


In [ ]:
s= input()
mod_s= '  '.join(s.split()) # Add two spaces between each word

uli min


In [ ]:
print(mod_s)

uli  min


# L= [8, 9.0, 'hry']
# l.sort()
# l.reverse()
# l.append(2)- appends 2 at the end of the list
# l.insert(3,8)- add 8 at 3 index
# l.pop(2)- delete elemets at index 2
# l.remove(21)- from the list

write a program to list seven fruits

In [ ]:
fruit= []
f1= input()
fruit.append(f1)
f2= input()
...# like this we append it


In [ ]:
marks=[]
print(marks.sort())

To prove tuple is immutable

In [ ]:
tuple=(1,2.0, 'harry')
tuple[2]='larry'
print(tuple)

TypeError: 'tuple' object does not support item assignment

using list to replace

In [ ]:
list=[1,2.0,'klit']
list[2]='kite'
print(list)

[1, 2.0, 'kite']


to count the no of zeros in a list

In [ ]:
list= [7, 0, 8, 0, 0, 9]
print(list.count(0))

3


dictionary

In [ ]:
dict= {"name": "madhu", "from": "india", "marks": [92,98,96]}
dict.items()

dict_items([('name', 'madhu'), ('from', 'india'), ('marks', [92, 98, 96])])

returns a list of key, value tuples

In [ ]:
dict.keys()

dict_keys(['name', 'from', 'marks'])

In [ ]:
dict.update({'friends':})

SyntaxError: expression expected after dictionary key and ':' (ipython-input-3091912573.py, line 1)

In [ ]:
dict.get('name')

'madhu'

#sets cannot conatin duplicate values
#sets are unindexed

In [ ]:
s= {1,2,8,6}

len(s)
s.remove(8)
s.pop()- ?
s.clear()
s.union({8,11})
s.intersection({8,11})

to get unique numbers

In [ ]:
numbers = [1, 2, 2, 3, 4, 4, 5, 1]
un= set(numbers)
print(un)

{1, 2, 3, 4, 5}


Yes — a set in Python can contain different types of data, as long as all elements are hashable (immutable).


In [ ]:
my_set = {42, "hello", 3.14, True, (1, 2)}
print(my_set)

invalid_set = {1, [2, 3], {"a": 1}}
# that will cause an error

In [ ]:
s={}
print(type(s))

<class 'dict'>


to add elements in set, list, tuple and dictionary we use diff commands- dict use update, set use add, list and tuple use update

In [ ]:
d = {}

name = input("Enter friends name: ")
lang = input("Enter Language name: ")
d.update({name: lang})

name = input("Enter friends name: ")
lang = input("Enter Language name: ")
d.update({name: lang})

name = input("Enter friends name: ")
lang = input("Enter Language name: ")
d.update({name: lang})

name = input("Enter friends name: ")
lang = input("Enter Language name: ")
d.update({name: lang})


print(d)

In [ ]:
s = {8, 7, 12, "Harry", [1,2]}

s[4] = 9

TypeError: unhashable type: 'list'

why inside a set () this is acceptd not {} or []

sum of n numbers

In [ ]:
def running_total(m)
 return m(m+1)/2
print(running_total(m))

is their any other way, i did this because i remember the formula

given marks of three subjects define a function to compare total passing marks

In [ ]:
mark1= input()
mark2= input()
mark3= input()

total_percen= (100*(mark1+mark2+mark3))/300
def compare(total_percen):
  if (total_percen>=40 and mark1>=33 and mark2>=33 and mark3>=33):
    return True
  else:
    return False

spam content is given p1,p2, p3 and p4

In [ ]:
p1 = "Make a lot of money"
p2 = "buy now"
p3 = "subscribe this"
p4 = "click this"
comment= input()

def detect_spam(comment):
  if ((p1 in comment) or (p2 in comment) or (p3 in comment) or (p4 in comment)):
    print ('True')

  else:
    print ('False')

buy now


In [ ]:
p1 = "Make a lot of money"
p2 = "buy now"
p3 = "subscribe this"
p4 = "click this"

message = input("Enter your comment: ")

if((p1 in message) or (p2 in message )or (p3 in message) or (p4 in message)):
    print("This comment is a spam")

else:
    print("This comment is not a spam")

Enter your comment: buy now
This comment is a spam


compare why upper one did not work

When to use count and len?

write to find out whether a given username has lees than 10

In [ ]:
charac= input()

if len(charac)>=10:
 print('yes')
else:
  print('no')

swa@87ytr
no


Check if your name is in the list

In [ ]:
l = ["Harry", "Rohan", "Shubham", "Divya"]
nam= input()
if nam in l:
  print('yes')
else:
  print('no')

diva
no


write a program to grade your marks

In [ ]:
marks= input()
if (marks<=100 and marks>=90):
  print('ex')

In [ ]:
marks = int(input("Enter your marks: "))

if(marks<=100 and marks>=90):
    grade = "Ex"
elif(marks<90 and marks>=80):
    grade = "A"
elif(marks<80 and marks>=70):
    grade = "B"
elif(marks<70 and marks>=60):
    grade = "C"
elif(marks<60 and marks>=50):
    grade = "D"
elif(marks<50):
    grade = "F"

print("Your grade is:", grade)

write a program to find out if a post is talking about harry or not

In [ ]:
post = input()

if ('harry' in post.lower()):
  print('yes')
else:
  print('no')

i like harry potters
yes


While loop- this block keeps executing until the condition is true
-body of the loop

in while loop, condition is executed first if the evaluation is true then the body of the loop is executed otherwise not.

In [ ]:
i = 1
while (i <6):
  print(i)
  i +=1


1
2
3
4
5


In [ ]:
l= []
i =0
while(i<len(l))
 print(l[i])
 i +=1

for loop is used to iterate through sequence like list, tuples etc

range function is used in python to generate a sequence of numbers
# range(start, stop, step_size)

an optional else can be used with for loop if the loop is to be executed after it gets exhausted

write a program to print multiplication table of a given number using for loop.

In [ ]:
n= int(input())
for i in range(1,10):
   print(n*i)

2
2
4
6
8
10
12
14
16
18


it excludes the stop range, gets us theresult before the mentioned stop range

writa program to greet all the person's name in the list starting with s

In [ ]:
l = ["Harry", "Soham", "Sachin", "Rahul"]
for i in l:
  if (i.startswith('s')):
   print(f'hello{i}')

In [ ]:
l = ["Harry", "Soham", "Sachin", "Rahul"]

for name in l:
    if(name.startswith("S")):
        print(f"Hello {name}")

Hello Soham
Hello Sachin


i think diff between the above and below code is that of case sensitiveness

use to code to print a multiplication table. tried with the above code replacing for with while- didnt work out

In [ ]:
n= int(input())
for i in range(1,10):
   print(n*i)

3
3
6
9
12
15
18
21
24
27


In [ ]:
n = int(input("Enter a number: "))

i = 1

while(i<11):
    print(f"{n} X {i} = {n * i}")
    i += 1

Enter a number: 10
10 X 1 = 10
10 X 2 = 20
10 X 3 = 30
10 X 4 = 40
10 X 5 = 50
10 X 6 = 60
10 X 7 = 70
10 X 8 = 80
10 X 9 = 90
10 X 10 = 100


write a program to find out i the given number is prime or not

In [ ]:
n = int(input())
for i in range(2,n):
 if i%2==0:
  print("no is not prime")
  break
 else:
  print('no is prime')

10
no is not prime


write a program to find the sum of first n natural numbers using while loop.

In [ ]:
n= int(input())
i = 1
sum=0
while(i<n+1)
 sum +=i
 i +=1
print(sum)

In [ ]:
n= int(input())
for i in range(1,n+1):
  i+1
  print(i)

3
1
2
3


i+1 does nothing — it calculates i+1 but doesn’t store it anywhere. In Python, integers are immutable, so you need i += 1 to actually increment.

but there;s also a one liner formula

In [ ]:
n= int(input())
sum=0
for i in range(1,n+1):
  sum+=i
  print(sum)

3
1
3
6


to calculate the factorial of a given no

In [ ]:
n= int(input())
fact=1
for i in range(1,n+1)
  fact*=i
  print(i)

In [ ]:
import math

def factorial(n):
    return(math.factorial(n))

# Driver Code
num = 5
print(factorial(num))

write a program using functions to find the greatest of three numbers

In [ ]:
a= int(input())
b=int(input())
c=int(input())

def greatest_no(a,b,c):
   if a>b and a>c:
    print(a)
   if b>a and b>c:
    print(b)
   else:
    print(c)

In [ ]:
list=[]
list.sort()
def great_three(list):
  return list[-1:-4]

write a function to convrt celsius to fahrenheit

In [ ]:
c= float(input())
def convert_f(c):
 return((c*(9/5))+32)

73.6


In [ ]:
print(convert_f(c))

164.48


checked the answer it is correct

how do you prevent a python print function to print a line in the end.

In [ ]:
print("Hello, ", end='')
print("world!")

Hello, world!


removing the end

In [ ]:
print("Hello")
print("world!")

Hello
world!


Functions to convert inches to cm

In [ ]:
inches= int(input())
def convert_tocm(inches):
  return(inches*2.54)
print(convert_tocm(inches))

3
7.62


write a python function to remove a word from the list and add it at the same place

In [ ]:
list = [" apple ", "banana", "  apple  ", "grape"]
def replace(mango, banana_word):
 for i in range(len(list)):
  list[i]= list[i].strip()
  if list[i]=='banana_word':
   list[i]=='mango'
  return list
print(replace(mango, banana))

NameError: name 'mango' is not defined

In [ ]:
fruits = [" apple ", "banana", "  apple  ", "grape"]

fruits = ["mango" if fruit.strip() == "banana" else fruit.strip() for fruit in fruits]

print(fruits)


['apple', 'mango', 'apple', 'grape']


is called a list comprehension with a conditional expression.
Let’s break it step-by-step:

for fruit in fruits

Loops over each element of the list fruits and stores it in fruit.

Example loop values: " apple ", "banana", " apple ", "grape".

fruit.strip()

Removes whitespace at the start and end of the string.

" apple " → "apple", " apple " → "apple".

if fruit.strip() == "banana" else fruit.strip()

This is a conditional expression (like a mini if-else in one line).

It means:

If the stripped fruit is "banana", use "mango".

Otherwise, just use the stripped fruit as it is.

Wrapping it all in [...]

Collects all the processed results into a new list.

Print a program of a multiplication table for a given number

Catch the difference between three codes. why only the last code ran

In [ ]:
n=int(input())

def multi_table(n):
 for i in range(1, 11):
    return n*i
print(multi_table(n))


3
3


In [ ]:
n = int(input())
def multi_table(n):
    for i in range(1, 11):
        print(n*i)

3


In [ ]:
def multi_table(n):
    for i in range(1, 11):
        print(f"{n} x {i} = {n*i}")

n = int(input())
multi_table(n)


3
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30


abdc